---
title: "Pajareadas en Caldas y Quindio"
author: "Sandra Rairán"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    social: menu
    source_code: embed
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(tidyr)
library(RColorBrewer)
library(tidyverse)
library(lubridate)
library(janitor)
library(vroom)
#library(broom)
#library(hrbrthemes)

#------------------ Parameters ------------------
# Set colors
# https://www.w3.org/TR/css-color-3/#svg-color
count_color <- "mediumvioletred"
active_color <- "orange"
recovered_color <- "forestgreen"
Durationmin_color <- "teal"

MyEBirdData<- read.csv("data/MyEBirdData.csv")
#data(MyEBirdData)
#str(MyEBirdData1)

#------------------ Data ------------------

#df1 <- MyEBirdData1 %>% dplyr::filter(Date == max(Date))

df_count <- MyEBirdData %>%  
  dplyr::group_by(Submission.ID, Date) %>%
  dplyr::mutate(count_cum = sum(MyEBirdData$Duration..Min))
                
bird_cantidad <- MyEBirdData %>% group_by( MyEBirdData$Submission.ID, MyEBirdData$Date )
birdcantidad <- bird_cantidad  %>% summarise(n = n())

# Minutos obervados por id de pajareo
bird_duracion_minuto <- MyEBirdData %>% group_by( MyEBirdData$Submission.ID, MyEBirdData$Date, MyEBirdData$Duration..Min.  )
birdduracionminuto <- bird_duracion_minuto  %>% summarise(n = n())

df <- MyEBirdData %>% 
mutate_at(vars(Submission.ID, Location, Date, Time, Protocol), str_replace_na, "NA") %>% 
  mutate(observation_event_id = str_c(Submission.ID, Location, Date, Time, sep = "-"),
         observation_date = ymd(Date)) 

#Cantidad por protocolo estacionario o con desplaazamiento
df_top_protocols <- df %>% 
  count(Protocol, sort = TRUE) %>% 
  slice(1:2)

df <- df %>% 
  semi_join(df_top_protocols) 

df %>% 
  select(Common.Name, Date, Count) %>% 
  glimpse()

#Grafica
# transformamos los meses en vector con los nombres de los meses
meses <- df %>% 
  mutate(observacion_mes = month(observation_date, label = TRUE)) %>% 
  distinct(observacion_mes) %>% 
  pull(observacion_mes)
# Observaciones por mes de espcies
df_observaciones <- df %>% 
  mutate(observacion_mes = month(observation_date, label = TRUE),
         observacion_año = year(observation_date)) %>% 
  group_by(Common.Name, observacion_año, observacion_mes) %>% 
  summarize(observation_count = sum(Count, na.rm = TRUE)) %>% 
  group_by(Common.Name, observacion_mes) %>% 
  summarize(observation_count_mean = mean(observation_count) %>% round(1)) %>% 
  ungroup() %>% 
  complete(Common.Name, observacion_mes = meses) %>% 
  replace_na(list(observation_count_mean = 0)) %>% 
  arrange(Common.Name, observacion_mes)
  glimpse(df_observaciones)
  
  
  df_observaciones <- df_observaciones %>% 
  mutate(observation_count_mean_log10 = log10(observation_count_mean),
         observation_count_mean_log10 = case_when(is.infinite(observation_count_mean_log10) ~ 0,
                                                  TRUE ~ observation_count_mean_log10)) %>% 
  select(-observation_count_mean)
  
  
  #Tendencias onservacion aves por especie

  veccommonname <- df_observaciones %>% 
  pivot_wider(names_from = observacion_mes, values_from = observation_count_mean_log10, names_prefix = "month_") %>% 
  clean_names() %>% 
  arrange(month_jan, month_feb, month_mar, month_apr, month_may, month_jun, month_jul, month_aug, month_sep, month_oct, month_nov,   month_dec) %>% 
  pull(1)
  
  
  # k-means-(Grupos )
   # k-means-(Grupos )
  
  
  df_observaciones_aves <- df_observaciones %>% 
  select(Common.Name, observacion_mes, observation_count_mean_log10) %>% 
  pivot_wider(names_from = observacion_mes, values_from = observation_count_mean_log10, names_prefix = "month_") %>% 
  clean_names()

  glimpse(df_observaciones_aves)
  
 
library(purrr)
library(tibble)
library(tidyr)
library(broom)
  kclusts <- tibble(k = 1:9) %>%
  mutate(
    kclust = map(k, ~kmeans(df_observaciones_aves %>% select(-common_name), .x)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, df_observaciones_aves %>% select(-common_name))
  )

kclusts

 clusters <- kclusts %>%
  unnest(tidied)

 assignments <- kclusts %>% 
  unnest(augmented)

 clusterings <- kclusts %>%
  unnest(glanced)
  
```


Resumen
=======================================================================


Row {data-width=450}
-----------------------------------------------------------------------

### Count {.value-box}

```{r}



valueBox(
  value = paste(format(sum(birdcantidad$n ), big.mark = ","), "", sep = " "),
  caption = "Total de Aves Observadas",
  icon = "far fa-smile",
  color = count_color
)


```




### Duration..Min. {.value-box}
```{r}

valueBox(
  value = paste(format(sum(birdduracionminuto$`MyEBirdData$Duration..Min.` ), big.mark = ","), "", sep = " "),
  caption = "Total Minutos Pajareando",
  icon = "far fa-smile",
  color = Durationmin_color
)

```

Row {data-height=600}
------------------------------------------------------------------------------
### Aves observadas segun el Duration..Min.
    
```{r}
library(tidyverse)
#Color al histograma
ggplot()+geom_histogram(data=MyEBirdData,
                        aes(x=Duration..Min.),fill="yellow",color="blue",
                        binwidth = 20)+
  labs(x="Tiempo observacion aves-minutos", y="Cantidad de Aves",
       title = "aves observadas segun el tiempo en minutos")+
  theme(legend.position = "none")+
  theme(panel.background = element_blank(),panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
 

  

```



### Aves observadas segun el tiempo en minutos

```{r}




  plotly::plot_ly(data = MyEBirdData) %>%
  plotly::add_trace(x = ~ MyEBirdData$Duration..Min,
                    y = ~ MyEBirdData$Count,
                    type = "bar", 
                name = "Active",
                marker = list(color = active_color)) %>%
  plotly::layout(barmode = 'stack',
                 yaxis = list(title = "Cantidad de Aves",
                              type = "log"),
                 xaxis = list(title = "Duracion observacion en Minutos"),
                 hovermode = "compare",
                  margin =  list(
                   # l = 60,
                   # r = 40,
                   b = 10,
                   t = 10,
                   pad = 2
                 ))


```

Graficas
=======================================================================
Column {data-width=400}
------------------------------------------------------------------------------
### Observaciones
```{r}
     
df %>% 
  count(observation_date) %>% 
  ggplot(aes(x = observation_date, y=n, group = 1)) +
  geom_line( colour = "mediumvioletred", size=1, alpha=0.9, linetype=1) +
   geom_point(color="mediumvioletred", size=2) +
  ggtitle("Observaciones por fecha") +
    labs(x = "Fecha Observacion",
         y = "Observacoines")+
   theme_light()


                         
```

### Observaciones por mes
```{r}

# log10 para Para hacer que los datos con asimetría positiva sean más "normales"
  df_observaciones %>% 
  ggplot(aes(observacion_mes, observation_count_mean_log10)) +
  geom_jitter(color="mediumorchid", size=0.7, alpha=0.5) +
    geom_boxplot(fill = "palegreen", colour = "mediumseagreen") +
    labs(x = "Observaciones por mes",
         y = "Promedio de aves observadas (log10)")+
  theme_light()

```

### Observaciones por mes
```{r}

# log10 para Para hacer que los datos con asimetría positiva sean más "normales"
  df_observaciones %>% 
  ggplot(aes(observacion_mes, observation_count_mean_log10)) +
     geom_point(color="purple", alpha=0.8) +
    labs(x = "Observaciones por mes",
         y = "Promedio de aves observadas (log10)")

```

      
Tendencias observacion
=======================================================================

Column {data-height=600}
-----------------------------------------------------------------------

###  Tendencias observacion aves por especie.

```{r}
df_observaciones %>%
  mutate(common_name = factor(Common.Name, levels = veccommonname)) %>%
  ggplot(aes(observacion_mes, Common.Name, fill = observation_count_mean_log10)) +
    geom_tile() +
  scale_fill_viridis_c("Promedio Observación (log10)") +
    #scale_fill_viridis_c(option = "plasma","Promedio Observación (log10)") +
  #scale_fill_viridis_b("Promedio Observación (log10)")+
    scale_x_discrete(expand = c(0,0)) +
    scale_y_discrete(expand = c(0,0)) +
    labs(x = "Observacion por mes",
         y = "Especies") +
    theme(panel.grid = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank())   

```

k-means-(Grupos )
=======================================================================

Column {data-height=600}
-----------------------------------------------------------------------
```{r}
ggplot(clusterings, aes(k, tot.withinss)) +
  geom_line() +
  geom_vline(xintercept = 2, linetype = 2) +
  geom_vline(xintercept = 4, linetype = 2) +
  scale_x_continuous(breaks = seq(1:9)) +
  labs(x = "Number of clusters")
```

```{r}


```


